const PAGE=document.body.dataset.page||'';
document.body.insertAdjacentHTML('afterbegin','<a class="skip-link" href="#main-content">Ana içeriğe geç</a>');
const main=document.querySelector('main');if(main)main.id='main-content';
const icon=document.createElement('link');icon.rel='icon';icon.type='image/svg+xml';icon.href='logo.svg';document.head.appendChild(icon);
if(!document.querySelector('link[rel="canonical"]')){const canonical=document.createElement('link');canonical.rel='canonical';canonical.href='https://toprakgrupglobal.com.tr/'+(location.pathname.split('/').pop()||'');document.head.appendChild(canonical)}
const currentFile=location.pathname.split('/').pop()||'index.html';
if(!document.querySelector('meta[name="robots"]')){const robots=document.createElement('meta');robots.name='robots';robots.content='index,follow,max-image-preview:large';document.head.appendChild(robots)}
const header=document.getElementById('site-header');
if(header)header.innerHTML=`<header class="header"><div class="nav-shell"><div class="wrap"><nav class="nav"><a class="brand" href="index.html" aria-label="Toprak Grup Global ana sayfa"><span class="brand-frame"><img class="logo" src="logo.svg" alt="TOPRAK GRUP GLOBAL GIDA İNŞAAT İTHALAT İHRACAT TİCARET VE SANAYİ LİMİTED ŞİRKETİ logosu"></span><span class="legal-brand"><b>TOPRAK GRUP GLOBAL</b><small>GIDA İNŞAAT İTHALAT İHRACAT<br>TİCARET VE SANAYİ LİMİTED ŞİRKETİ</small></span></a><div class="navlinks" id="navlinks"><a data-n="home" href="index.html">Ana Sayfa</a><a data-n="kurumsal" href="kurumsal.html">Kurumsal</a><a data-n="faaliyetler" href="faaliyetler.html">Faaliyetler</a><a data-n="urunler" href="urunler.html">Ürünler</a><a data-n="ag" href="ticaret-agi.html">Ticaret Ağı</a><a data-n="iletisim" href="iletisim.html">İletişim</a><a class="store-link" href="https://lastik.toprakgrupglobal.com.tr" target="_blank" rel="noopener">Lastik Mağazası <span>↗</span></a></div><div class="lang-switch" aria-label="Dil seçimi"><a class="active" href="${currentFile}">TR</a><a href="en/${currentFile}">EN</a><a href="fa/${currentFile}">FA</a><a href="ar/${currentFile}">AR</a></div><a class="header-cta" href="iletisim.html#teklif"><b>TEKLİF AL</b><span>→</span></a><button class="menu" id="menu" aria-label="Menüyü aç" aria-expanded="false">☰</button></nav></div></div></header>`;
const active=document.querySelector(`[data-n="${PAGE}"]`);if(active)active.classList.add('active');
const menu=document.getElementById('menu'),links=document.getElementById('navlinks');if(menu)menu.addEventListener('click',()=>{const o=links.classList.toggle('open');document.body.classList.toggle('lock',o);menu.setAttribute('aria-expanded',o);menu.textContent=o?'×':'☰'});
const footer=document.getElementById('site-footer');
if(footer)footer.innerHTML=`<footer class="footer"><div class="wrap"><div class="footer-grid"><div class="footer-brand"><a class="brand" href="index.html"><img class="logo" src="logo.svg" alt="TOPRAK GRUP GLOBAL GIDA İNŞAAT İTHALAT İHRACAT TİCARET VE SANAYİ LİMİTED ŞİRKETİ logosu"></a><p><strong>TOPRAK GRUP GLOBAL GIDA İNŞAAT İTHALAT İHRACAT TİCARET VE SANAYİ LİMİTED ŞİRKETİ</strong></p><p>İthalat, ihracat, lojistik, gıda, inşaat ve endüstriyel ürünlerde kurumsal B2B ticaret çözümleri.</p></div><div class="footer-col"><h4>KURUMSAL</h4><a href="kurumsal.html">Hakkımızda</a><a href="kalite-politikasi.html">Kalite Politikası</a><a href="insan-kaynaklari.html">İnsan Kaynakları</a><a href="faaliyetler.html">Faaliyet Alanları</a><a href="ticaret-agi.html">Ticaret Ağı</a><a href="iletisim.html">İletişim</a></div><div class="footer-col"><h4>ÜRÜNLER</h4><a href="gpps-1540.html">GPPS 1540</a><a href="lastik-granulu.html">Lastik Granülü</a><a href="celik-yapi-urunleri.html">Çelik Ürünleri</a><a href="muz-ticareti.html">Muz Ticareti</a><a href="hurma-ticareti.html">Hurma Ticareti</a><a href="urunler.html">Tüm Ürünler</a></div><div class="footer-col"><h4>YASAL</h4><a href="kvkk-aydinlatma.html">KVKK Aydınlatma</a><a href="gizlilik-politikasi.html">Gizlilik Politikası</a><a href="cerez-politikasi.html">Çerez Politikası</a><a href="ilgili-kisi-basvurusu.html">İlgili Kişi Başvurusu</a><a href="kullanim-kosullari.html">Kullanım Koşulları</a></div></div><div class="copy"><span>© 2026 Toprak Grup Global. Tüm hakları saklıdır.</span><span>Kışla Mahallesi, 65400 Van · +90 505 472 89 85</span></div></div></footer><a class="whatsapp" href="https://wa.me/905054728985?text=Merhaba%20Toprak%20Grup%20Global" target="_blank" rel="noopener" aria-label="WhatsApp ile iletişim"><b>✆</b><span> WhatsApp</span></a>`;
const form=document.getElementById('quoteForm');if(form)form.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(form),v=x=>encodeURIComponent(f.get(x)||'');window.open('https://wa.me/905054728985?text=Merhaba%20Toprak%20Grup%20Global%2C%0A%0A*Ad%2FFirma%3A*%20'+v('name')+'%0A*Telefon%3A*%20'+v('phone')+'%0A*E-posta%3A*%20'+v('email')+'%0A*Talep%3A*%20'+v('subject')+'%0A*Detay%3A*%20'+v('message'),'_blank','noopener')});
document.querySelectorAll('img:not(.logo)').forEach(img=>{img.loading='lazy';img.decoding='async'});
const productGrid=document.querySelector('[data-product-grid]');
if(productGrid){const cards=[...productGrid.querySelectorAll('.product-card')],buttons=[...document.querySelectorAll('[data-filter]')],search=document.getElementById('product-search'),sort=document.getElementById('product-sort');const update=()=>{const active=document.querySelector('[data-filter].active')?.dataset.filter||'all',q=(search?.value||'').toLocaleLowerCase('tr');cards.forEach(card=>{const okCategory=active==='all'||card.dataset.category===active;const okSearch=!q||card.textContent.toLocaleLowerCase('tr').includes(q);card.hidden=!(okCategory&&okSearch)});const visible=cards.filter(c=>!c.hidden);if(sort?.value==='az')visible.sort((a,b)=>a.dataset.name.localeCompare(b.dataset.name,'tr'));if(sort?.value==='za')visible.sort((a,b)=>b.dataset.name.localeCompare(a.dataset.name,'tr'));visible.forEach(c=>productGrid.appendChild(c));const count=document.getElementById('product-count');if(count)count.textContent=`${visible.length} ürün grubu gösteriliyor`};buttons.forEach(b=>b.addEventListener('click',()=>{buttons.forEach(x=>x.classList.remove('active'));b.classList.add('active');update()}));search?.addEventListener('input',update);sort?.addEventListener('change',update);update()}
